# Este é um fluxo de trabalho básico para ajudar você a começar com ações



name : CI



# Controla quando o fluxo de trabalho será executado

on :

 # Aciona o fluxo de trabalho em eventos de solicitação push ou pull, mas apenas para o branch "principal"

 push :

   branches : [ "main" ]

 pull_request :

   branches : [ "main" ]



 # Permite que você execute este fluxo de trabalho manualmente na guia Ações

 workflow_dispatch :



# Uma execução de fluxo de trabalho é composta de um ou mais trabalhos que podem ser executados sequencialmente ou em paralelo

jobs :

 # Este fluxo de trabalho contém um único trabalho chamado "build"

 build :

   # O tipo de executor no qual o trabalho será executado

   runs-on : ubuntu-latest



   # As etapas representam uma sequência de tarefas que serão executadas como parte do trabalho

   steps :

     # Faz check-out do seu repositório em $GITHUB_WORKSPACE, para que seu trabalho possa acessá-lo

     - uses : actions/checkout@v3



     # Executa um único comando usando o shell do runner

     - name : Executa um script de uma linha

       run : echo "Olá, mundo!"


     # Executa um conjunto de comandos usando o shell do runner

     - name : Executa um script multi-linha

       run : |

         echo "Adicionar outras ações para build"

         echo "Testar e implantar o projeto"
